/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPronoRouteImport } from './routes/_authenticated/prono'
import { Route as AuthenticatedKoSchemaRouteImport } from './routes/_authenticated/ko-schema'
import { Route as AuthenticatedKlassementRouteImport } from './routes/_authenticated/klassement'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfirmProfileRouteImport } from './routes/_authenticated/confirm-profile'
import { Route as AuthenticatedBonusRouteImport } from './routes/_authenticated/bonus'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHooksSyncResultsRouteImport } from './routes/api/public/hooks/sync-results'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPronoRoute = AuthenticatedPronoRouteImport.update({
  id: '/prono',
  path: '/prono',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKoSchemaRoute = AuthenticatedKoSchemaRouteImport.update({
  id: '/ko-schema',
  path: '/ko-schema',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKlassementRoute = AuthenticatedKlassementRouteImport.update({
  id: '/klassement',
  path: '/klassement',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfirmProfileRoute =
  AuthenticatedConfirmProfileRouteImport.update({
    id: '/confirm-profile',
    path: '/confirm-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBonusRoute = AuthenticatedBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksSyncResultsRoute =
  ApiPublicHooksSyncResultsRouteImport.update({
    id: '/api/public/hooks/sync-results',
    path: '/api/public/hooks/sync-results',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bonus': typeof AuthenticatedBonusRoute
  '/confirm-profile': typeof AuthenticatedConfirmProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/klassement': typeof AuthenticatedKlassementRoute
  '/ko-schema': typeof AuthenticatedKoSchemaRoute
  '/prono': typeof AuthenticatedPronoRoute
  '/api/public/hooks/sync-results': typeof ApiPublicHooksSyncResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bonus': typeof AuthenticatedBonusRoute
  '/confirm-profile': typeof AuthenticatedConfirmProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/klassement': typeof AuthenticatedKlassementRoute
  '/ko-schema': typeof AuthenticatedKoSchemaRoute
  '/prono': typeof AuthenticatedPronoRoute
  '/api/public/hooks/sync-results': typeof ApiPublicHooksSyncResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bonus': typeof AuthenticatedBonusRoute
  '/_authenticated/confirm-profile': typeof AuthenticatedConfirmProfileRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/klassement': typeof AuthenticatedKlassementRoute
  '/_authenticated/ko-schema': typeof AuthenticatedKoSchemaRoute
  '/_authenticated/prono': typeof AuthenticatedPronoRoute
  '/api/public/hooks/sync-results': typeof ApiPublicHooksSyncResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/bonus'
    | '/confirm-profile'
    | '/dashboard'
    | '/klassement'
    | '/ko-schema'
    | '/prono'
    | '/api/public/hooks/sync-results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/bonus'
    | '/confirm-profile'
    | '/dashboard'
    | '/klassement'
    | '/ko-schema'
    | '/prono'
    | '/api/public/hooks/sync-results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/bonus'
    | '/_authenticated/confirm-profile'
    | '/_authenticated/dashboard'
    | '/_authenticated/klassement'
    | '/_authenticated/ko-schema'
    | '/_authenticated/prono'
    | '/api/public/hooks/sync-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksSyncResultsRoute: typeof ApiPublicHooksSyncResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prono': {
      id: '/_authenticated/prono'
      path: '/prono'
      fullPath: '/prono'
      preLoaderRoute: typeof AuthenticatedPronoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ko-schema': {
      id: '/_authenticated/ko-schema'
      path: '/ko-schema'
      fullPath: '/ko-schema'
      preLoaderRoute: typeof AuthenticatedKoSchemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/klassement': {
      id: '/_authenticated/klassement'
      path: '/klassement'
      fullPath: '/klassement'
      preLoaderRoute: typeof AuthenticatedKlassementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/confirm-profile': {
      id: '/_authenticated/confirm-profile'
      path: '/confirm-profile'
      fullPath: '/confirm-profile'
      preLoaderRoute: typeof AuthenticatedConfirmProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bonus': {
      id: '/_authenticated/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof AuthenticatedBonusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/sync-results': {
      id: '/api/public/hooks/sync-results'
      path: '/api/public/hooks/sync-results'
      fullPath: '/api/public/hooks/sync-results'
      preLoaderRoute: typeof ApiPublicHooksSyncResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBonusRoute: typeof AuthenticatedBonusRoute
  AuthenticatedConfirmProfileRoute: typeof AuthenticatedConfirmProfileRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKlassementRoute: typeof AuthenticatedKlassementRoute
  AuthenticatedKoSchemaRoute: typeof AuthenticatedKoSchemaRoute
  AuthenticatedPronoRoute: typeof AuthenticatedPronoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBonusRoute: AuthenticatedBonusRoute,
  AuthenticatedConfirmProfileRoute: AuthenticatedConfirmProfileRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKlassementRoute: AuthenticatedKlassementRoute,
  AuthenticatedKoSchemaRoute: AuthenticatedKoSchemaRoute,
  AuthenticatedPronoRoute: AuthenticatedPronoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksSyncResultsRoute: ApiPublicHooksSyncResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
